### ISSUE TITLE
Query about the implements of MMMLP

### ISSUE THREAD

**Issue by Zhang-xiaokun** [Applied-Machine-Learning-Lab/MMMLP#3]
Thanks a lot for sharing codes of MMMLP!
I am very interested with your excellent work. Unfortunately, I have encountered some issues when implementing your model.
1. What is the format of the input? such as the exact format of sequence, image and text? Could you please show some instances of the input data? I think that some instances of the input data can help readers easily reproduce MMMLP.
2. How to run the MMMLP? There are only two files in the released codes. It did not tell too much implement details, like the used environment, the processing on original data or the ways on training/testing MMMLP. It seems that we need to replace the 'Baseline' with 'MMMLP' in the 'mlp4rec.py' and run the file 'mlp4rec'. Is that okey?
Thanks for your work again! 
I'm looking forward for your kindly response.

**Comment by Andy3117006664** [comment]
Thank you for your interest in MMMLP and for reaching out with your queries.

1. Input Data Format: The format of the input for MMMLP adheres to the standards set by the RecBole library. If you are familiar with RecBole, you can easily adapt your data to be compatible with MMMLP. For specific instances of the input data, it would be beneficial to refer to the RecBole documentation or their example datasets. This will provide a clear understanding of how sequence, image, and text data should be formatted.

2. Running MMMLP:  As mentioned in our paper, MMMLP is designed to run within the RecBole framework. To execute MMMLP, you should indeed place it within the appropriate directory of RecBole and run it as you would with any other model supported by the library. Replacing 'Baseline' with 'MMMLP' in 'mlp4rec.py' and then running 'mlp4rec' is a correct approach.

We truly appreciate your feedback and interest in our work. We will consider adding more detailed instructions and examples in the future to help users like you. Please let us know if you have any more questions or need further assistance.

**Comment by Zhang-xiaokun** [comment]
Thanks for your kindly response!
Although you have highlighted some features of MMMLP, unfortunately, we regrettably find that that it is still not easy to reproduce MMMLP. 
1. About the format of input data, especially item images and text. As you said, it is similar with Recbole. However, we have made some efforts to search the whole project of Recbole. Unfortunately, we could not find the ways on utilizing image or text (we searched the key word "image", "pkl" and so on). Therefore, I was wondering that could you please point out the specific position on Recbole for us. It will be very appreciated for your specific help.
2. About the input images or text. We do not catch the exact input format of them. Did we input original image or processed embeddings into the MMMLP? As you know, the UniSRec (KDD2022) of Recbole used the processed text embeddings as its input. 
3. In the  line 94 of 'mmmlp.py', it reads " MMMLP is similar with the mlpmixer implemented in RecBole". However, we could not find mlpmixer in the Recbole. I was wondering that could you kindly point the relevant codes for us.
4. Could you please detail how we can run the MMMLP? like, where we put the input data, how we can train the model as well as where we should place the codes of MMMLP in the Recbole codes.
5. It will be very helpful to reproduce MMMLP if you can give some input instances or release the input data on external links like google driven or something else.
Thanks again for your great work!
And, we are very appreciated the time and efforts you dedicated on providing guidance for us.
 I am looking forward for your kindly help.

**Comment by Andy3117006664** [comment]
1. **Utilizing Image or Text in RecBole:** RecBole generally doesn't handle raw image or text data directly. Instead, these data types are pre-processed into a suitable format. As mentioned in our paper, the image and text should be pre-processed as embeddings. I would kindly suggest revisiting our paper, as it provides clear guidelines on how the data should be prepared for MMMLP. By focusing on the paper's details, many of your concerns might be addressed.

2. **Input Format for Images and Text:** For MMMLP, you should provide processed embeddings rather than the original image or raw text data. Using embeddings ensures consistent input dimensions and compatibility with the model.

3. **Reference to 'mlpmixer':** I apologize for any confusion. The term "mlpmixer" refers to our modified model inspired by the "MLP-Mixer: An all-MLP Architecture for Vision (arXiv:2105.01601)" paper. To derive this model from MMMLP, you can simply remove the text and image modalities. 

4. **Running MMMLP:**
       - **Input Data:** Place the input data in the directory as specified by the RecBole framework for datasets.
       - **Training:** After positioning your data and integrating MMMLP into RecBole, use RecBole's standard training commands.
       - **Placement of MMMLP code:** Put the MMMLP code in the appropriate model directory within RecBole, akin to other model implementations.
